{"name": "Verify that the user is able to Edit Policy from Manual SWM successfully with web small dataset", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=57493): Max retries exceeded with url: /session/0b3dfa49fa5c43d24fcd379439bfbcef/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001494F294D70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 16, in after_step\n    allure.attach(context.driver.get_screenshot_as_png()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "description": "The objective of this test case is to ensure that the users can successfully Edit Policy from Manual SWM with web small dataset", "steps": [{"name": "Given The user is successfully logged in the yieldWerx web application", "status": "passed", "start": 1722842697249, "stop": 1722842708527}, {"name": "When Click \"SWM\" in the left menu bar", "status": "passed", "start": 1722842708527, "stop": 1722842708578}, {"name": "When Click \"Manual SWM\" and Manual SWM window will open", "status": "passed", "start": 1722842708579, "stop": 1722842710268}, {"name": "When Click and select Source Facility, the Source Work Center, Source Device, Source Test Program", "status": "passed", "start": 1722842710268, "stop": 1722842734961}, {"name": "When Select Source Lots (73631), Source Wafers (Probe Count = 1)", "status": "passed", "start": 1722842734961, "stop": 1722842734961}, {"name": "When Click and select Target Facility, Target Work Center, Target Device, Target Test Program", "status": "passed", "start": 1722842734961, "stop": 1722842749885}, {"name": "When Select Target Lots (73631), Target Wafers (Probe Count = 1), \"<Policies>\"", "status": "passed", "start": 1722842749885, "stop": 1722842749885}, {"name": "When Select \"Wafer Plotting Option\" from \"Calculated Wafer/Die Size Settings and Actual Wafer/Die Size Setting\"", "status": "passed", "start": 1722842749885, "stop": 1722842749945}, {"name": "When Click \"Generate Manual SWM\" button to generate Manual SWM Wafer", "status": "passed", "start": 1722842749945, "stop": 1722842752988}, {"name": "Then Manual SWM Wafer as Combine Bin Wafer Map with Wafer ID: MC will be generated and be shown", "status": "passed", "start": 1722842752988, "stop": 1722842771326}, {"name": "When Click \"Edit Policy\" button available top right side of window", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56495): Max retries exceeded with url: /session/2bcc1892a869a34ca1a8833698f0a7f8/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001494F19E390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 16, in after_step\n    allure.attach(context.driver.get_screenshot_as_png()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1722842771326, "stop": 1722842803928}, {"name": "When Create SWM Policy window will open and make changes in General, Input Data & Rule selection, Output Data Selection, and Manage exceptions tab that you want to modify", "status": "passed", "start": 1722842803930, "stop": 1722842815461}, {"name": "When Click \"Save\" button and Save Change", "status": "passed", "start": 1722842815461, "stop": 1722842815516}, {"name": "When After popup appears choose any option and click \"OK\" button to save the changes", "status": "passed", "start": 1722842815517, "stop": 1722842817108}, {"name": "Then Verify that the policy with made changes will be saved and Manual SWM will refresh", "status": "passed", "start": 1722842817108, "stop": 1722842844864}, {"name": "Given The user is successfully logged in the yieldWerx web application", "status": "passed", "start": 1722842844864, "stop": 1722842844865}, {"name": "When Click \"SWM\" in the left menu bar", "status": "passed", "start": 1722842844865, "stop": 1722842858393}, {"name": "When Click \"Manual SWM\" and Manual SWM window will open", "status": "passed", "start": 1722842858393, "stop": 1722842858394}, {"name": "When Click and select Source Facility, the Source Work Center, Source Device, Source Test Program", "status": "passed", "start": 1722842858394, "stop": 1722842858460}, {"name": "When Select Source Lots (73631), Source Wafers (Probe Count = 1)", "status": "passed", "start": 1722842858460, "stop": 1722842861521}, {"name": "When Click and select Target Facility, Target Work Center, Target Device, Target Test Program", "status": "passed", "start": 1722842861521, "stop": 1722842880906}, {"name": "When Select Target Lots (73631), Target Wafers (Probe Count = 1), \"<Policies>\"", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56983): Max retries exceeded with url: /session/29f22e183915aca5e45a60fc096df49e/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001494F1D7620>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 16, in after_step\n    allure.attach(context.driver.get_screenshot_as_png()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1722842880906, "stop": 1722842913649}, {"name": "When Select \"Wafer Plotting Option\" from \"Calculated Wafer/Die Size Settings and Actual Wafer/Die Size Setting\"", "status": "passed", "start": 1722842913650, "stop": 1722842925540}, {"name": "When Click \"Generate Manual SWM\" button to generate Manual SWM Wafer", "status": "passed", "start": 1722842925540, "stop": 1722842925597}, {"name": "Then Manual SWM Wafer as Combine Bin Wafer Map with Wafer ID: MC will be generated and be shown", "status": "passed", "start": 1722842925597, "stop": 1722842927278}, {"name": "When Click \"Edit Policy\" button available top right side of window", "status": "passed", "start": 1722842927278, "stop": 1722842938489}, {"name": "When Create SWM Policy window will open and make changes in General, Input Data & Rule selection, Output Data Selection, and Manage exceptions tab that you want to modify", "status": "passed", "start": 1722842938489, "stop": 1722842938489}, {"name": "When Click \"Save\" button and Save Change", "status": "passed", "start": 1722842938489, "stop": 1722842945052}, {"name": "When After popup appears choose any option and click \"OK\" button to save the changes", "status": "passed", "start": 1722842945052, "stop": 1722842945052}, {"name": "Then Verify that the policy with made changes will be saved and Manual SWM will refresh", "status": "passed", "start": 1722842945052, "stop": 1722842945144}, {"name": "Given The user is successfully logged in the yieldWerx web application", "status": "passed", "start": 1722842945144, "stop": 1722842948261}, {"name": "When Click \"SWM\" in the left menu bar", "status": "passed", "start": 1722842948261, "stop": 1722842966894}, {"name": "When Click \"Manual SWM\" and Manual SWM window will open", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=57493): Max retries exceeded with url: /session/0b3dfa49fa5c43d24fcd379439bfbcef/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001494F294D70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 16, in after_step\n    allure.attach(context.driver.get_screenshot_as_png()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1722842966894, "stop": 1722842999106}, {"name": "When Click and select Source Facility, the Source Work Center, Source Device, Source Test Program", "status": "passed", "start": 1722842999106, "stop": 1722842999106}, {"name": "When Select Source Lots (73631), Source Wafers (Probe Count = 1)", "status": "passed", "start": 1722842999106, "stop": 1722842999106}, {"name": "When Click and select Target Facility, Target Work Center, Target Device, Target Test Program", "status": "passed", "start": 1722842999106, "stop": 1722842999106}, {"name": "When Select Target Lots (73631), Target Wafers (Probe Count = 1), \"<Policies>\"", "status": "passed", "start": 1722842999106, "stop": 1722842999106}, {"name": "When Select \"Wafer Plotting Option\" from \"Calculated Wafer/Die Size Settings and Actual Wafer/Die Size Setting\"", "status": "passed", "start": 1722842999106, "stop": 1722842999106}, {"name": "When Click \"Generate Manual SWM\" button to generate Manual SWM Wafer", "status": "passed", "start": 1722842999106, "stop": 1722842999106}, {"name": "Then Manual SWM Wafer as Combine Bin Wafer Map with Wafer ID: MC will be generated and be shown", "status": "passed", "start": 1722842999106, "stop": 1722842999106}, {"name": "When Click \"Edit Policy\" button available top right side of window", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=57493): Max retries exceeded with url: /session/0b3dfa49fa5c43d24fcd379439bfbcef/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001494F294D70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 16, in after_step\n    allure.attach(context.driver.get_screenshot_as_png()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shahbaz.hanif\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1722842999106, "stop": 1722842999106}, {"name": "When Create SWM Policy window will open and make changes in General, Input Data & Rule selection, Output Data Selection, and Manage exceptions tab that you want to modify", "status": "skipped", "start": 1722842999106, "stop": 1722842999106}, {"name": "When Click \"Save\" button and Save Change", "status": "skipped", "start": 1722842999106, "stop": 1722842999106}, {"name": "When After popup appears choose any option and click \"OK\" button to save the changes", "status": "skipped", "start": 1722842999106, "stop": 1722842999106}, {"name": "Then Verify that the policy with made changes will be saved and Manual SWM will refresh", "status": "skipped", "start": 1722842999106, "stop": 1722842999106}], "start": 1722842697247, "stop": 1722842999106, "uuid": "44272d66-b519-4ea5-8bac-800145f019d7", "historyId": "8fa5b1ff96566685d72f623f3bbbb8ac", "fullName": "SWM Policies: Verify that the user is able to Edit Policy from Manual SWM successfully with web small dataset", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "YWPD-TC-335"}, {"name": "tag", "value": "retry"}, {"name": "feature", "value": "SWM Policies"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}